server:
  port: 8080 # ???? ?? ???

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # CORS 전역 설정
      globalcors:
        cors-configurations:
          '[/**]': # 모든 경로에 대해 CORS 정책 적용
            allowedOrigins: "http://localhost:8085"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        # 공개 경로: 로그인, 회원가입 API는 필터를 적용하지 않습니다.
        - id: user-service-public
          uri: ${SERVICE_USER_URI}
          predicates:
            - Path=/api/members/login/**, /api/members/register/**

        - id: user-service
          uri: ${SERVICE_USER_URI}
          predicates:
            - Path=/api/members/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: ${SERVICE_PRODUCT_URI}
          predicates:
            - Path=/api/products/**, /api/admin/products/**
          filters:
            - AuthenticationFilter

        - id: wish-service
          uri: ${SERVICE_WISH_URI}
          predicates:
            - Path=/api/wishes/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: ${SERVICE_ORDER_URI}
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

# JWT Secret Key (user-service? ??? ? ??)
jwt:
  secret: ${JWT_SECRET}