server:
  port: 8085 # ???? ?? ???

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter

      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/members/**

        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**, /api/admin/products/**

        - id: wish-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/wishes/**

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**

# JWT Secret Key (user-service? ??? ? ??)
jwt:
  secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=